namespace HelpDeskPro.Api.Models;
public enum Role { Admin, Support, Employee }
public enum TicketStatus { Open, InProgress, Pending, Resolved, Closed }
public enum Priority { Low, Medium, High, Critical }
public class Department { public int Id {get;set;} public string Name {get;set;}=""; public ICollection<User> Users {get;set;}=new List<User>(); public ICollection<Ticket> Tickets {get;set;}=new List<Ticket>(); }
public class User { public int Id {get;set;} public string FullName {get;set;}=""; public string Email {get;set;}=""; public string PasswordHash {get;set;}=""; public Role Role {get;set;} public int? DepartmentId {get;set;} public Department? Department {get;set;} public bool IsActive {get;set;}=true; public DateTime CreatedAt {get;set;}=DateTime.UtcNow; public ICollection<Ticket> CreatedTickets {get;set;}=new List<Ticket>(); public ICollection<Ticket> AssignedTickets {get;set;}=new List<Ticket>(); }
public class Ticket { public int Id {get;set;} public string Title {get;set;}=""; public string Description {get;set;}=""; public TicketStatus Status {get;set;}=TicketStatus.Open; public Priority Priority {get;set;}=Priority.Medium; public DateTime CreatedAt {get;set;}=DateTime.UtcNow; public DateTime? UpdatedAt {get;set;} public DateTime? ResolvedAt {get;set;} public DateTime SlaDueAt {get;set;} public string Tags {get;set;}=""; public int? Rating {get;set;} public string? RatingComment {get;set;} public int CreatedById {get;set;} public User CreatedBy {get;set;}=null!; public int? AssignedToId {get;set;} public User? AssignedTo {get;set;} public int? DepartmentId {get;set;} public Department? Department {get;set;} public ICollection<TicketComment> Comments {get;set;}=new List<TicketComment>(); public ICollection<TicketAttachment> Attachments {get;set;}=new List<TicketAttachment>(); }
public class TicketComment { public int Id {get;set;} public string Body {get;set;}=""; public DateTime CreatedAt {get;set;}=DateTime.UtcNow; public int TicketId {get;set;} public Ticket Ticket {get;set;}=null!; public int UserId {get;set;} public User User {get;set;}=null!; }
public class TicketAttachment { public int Id {get;set;} public string FileName {get;set;}=""; public string StoredName {get;set;}=""; public string ContentType {get;set;}="application/octet-stream"; public long Size {get;set;} public DateTime CreatedAt {get;set;}=DateTime.UtcNow; public int TicketId {get;set;} public Ticket Ticket {get;set;}=null!; public int UploadedById {get;set;} }
public class KnowledgeArticle { public int Id {get;set;} public string Title {get;set;}=""; public string Category {get;set;}=""; public string Content {get;set;}=""; public DateTime UpdatedAt {get;set;}=DateTime.UtcNow; public int AuthorId {get;set;} }
public class ActivityLog { public int Id {get;set;} public string Action {get;set;}=""; public string Entity {get;set;}=""; public int? EntityId {get;set;} public int? UserId {get;set;} public DateTime CreatedAt {get;set;}=DateTime.UtcNow; }
public class Notification { public int Id {get;set;} public string Title {get;set;}=""; public string Message {get;set;}=""; public string Type {get;set;}="info"; public bool IsRead {get;set;} public DateTime CreatedAt {get;set;}=DateTime.UtcNow; public int UserId {get;set;} }
