import { useEffect, useState } from 'react';
import { BookOpen, Plus, Trash2, X, ArrowRight } from 'lucide-react';
import api from '../services/api';
import { Link } from 'react-router-dom';

export default function Knowledge() {
  const [articles,setArticles]=useState([]); const [showModal,setShowModal]=useState(false); const [form,setForm]=useState({title:'',content:'',category:'General'}); const [error,setError]=useState(''); const [saving,setSaving]=useState(false);
  const load=async()=>{try{const r=await api.get('/knowledge');setArticles(Array.isArray(r.data)?r.data:[])}catch(e){setError(e.response?.data?.message||'Unable to load articles.')}};
  useEffect(()=>{let mounted=true;const run=async()=>{try{const r=await api.get('/knowledge');if(mounted)setArticles(Array.isArray(r.data)?r.data:[])}catch(e){if(mounted)setError(e.response?.data?.message||'Unable to load articles.')}};run();return()=>{mounted=false}},[]);
  const add=async e=>{e.preventDefault();setSaving(true);setError('');try{await api.post('/knowledge',{...form,authorId:1});setForm({title:'',content:'',category:'General'});setShowModal(false);await load()}catch(e){setError(e.response?.data?.message||'Unable to add article.')}finally{setSaving(false)}};
  const del=async id=>{if(!window.confirm('Delete this article?'))return;try{await api.delete('/knowledge/'+id);await load()}catch(e){setError(e.response?.data?.message||'Unable to delete article.')}};
  return <><div className="pageHead"><div><h2>Knowledge Base</h2><p>Self-service articles for common IT problems.</p></div><button className="primary" onClick={()=>{setError('');setShowModal(true)}}><Plus size={17}/> Add Article</button></div>{error&&!showModal&&<div className="errorBox">{error}</div>}<div className="cardsGrid">{articles.map(x=><article className="article" key={x.Id}><Link className="articleOpen" to={`/knowledge/${x.Id}`}><BookOpen size={22}/><em>{x.Category}</em><h3>{x.Title}</h3><p>{x.Content}</p><span className="readMore">View solution <ArrowRight size={14}/></span></Link><button onClick={()=>del(x.Id)}><Trash2 size={15}/> Delete</button></article>)}</div>{showModal&&<div className="modal" onMouseDown={e=>e.target===e.currentTarget&&!saving&&setShowModal(false)}><div className="modalCard"><button className="close" type="button" onClick={()=>!saving&&setShowModal(false)}><X size={18}/></button><h2>Add Knowledge Article</h2><p className="modalSub">Create a helpful article for employees and support agents.</p><form onSubmit={add} className="stackForm"><label>Title<input required value={form.title} placeholder="e.g. Reset your password" onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Category<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}><option>General</option><option>Accounts</option><option>Network</option><option>Hardware</option><option>Software</option></select></label><label>Content<textarea required value={form.content} placeholder="Write the solution or instructions..." onChange={e=>setForm({...form,content:e.target.value})}/></label>{error&&<div className="error">{error}</div>}<div className="modalActions"><button type="button" className="secondary" onClick={()=>!saving&&setShowModal(false)}>Cancel</button><button className="primary" disabled={saving}>{saving?'Creating...':'Create Article'}</button></div></form></div></div>}</>;
}
