using HelpDeskPro.Api.Data; using HelpDeskPro.Api.Models; using Microsoft.AspNetCore.Authorization; using Microsoft.AspNetCore.Identity; using Microsoft.AspNetCore.Mvc; using Microsoft.EntityFrameworkCore;
namespace HelpDeskPro.Api.Controllers;
[ApiController][Route("api/users")][Authorize]
public class UsersController:ControllerBase {
 private readonly AppDbContext db; private readonly PasswordHasher<User> hasher=new();
 public UsersController(AppDbContext db){this.db=db;} int GetUserId()=>int.Parse(User.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier)!.Value);
 [HttpGet] public async Task<IActionResult> Get()=>Ok(await db.Users.Include(x=>x.Department).Select(x=>new{x.Id,x.FullName,x.Email,Role=x.Role.ToString(),Department=x.Department==null?null:x.Department.Name,x.IsActive,x.CreatedAt}).ToListAsync());
 public class CreateUserRequest { public string FullName {get;set;}=""; public string Email {get;set;}=""; public string Password {get;set;}="123456"; public Role Role {get;set;}=Role.Employee; public int? DepartmentId {get;set;} public bool IsActive {get;set;}=true; }
 [Authorize(Roles="Admin")][HttpPost] public async Task<IActionResult> Add(CreateUserRequest input){ if(string.IsNullOrWhiteSpace(input.FullName)||string.IsNullOrWhiteSpace(input.Email)) return BadRequest(new{message="Full name and email are required."}); if(await db.Users.AnyAsync(x=>x.Email==input.Email)) return Conflict(new{message="A user with this email already exists."}); var user=new User{FullName=input.FullName.Trim(),Email=input.Email.Trim(),Role=input.Role,DepartmentId=input.DepartmentId,IsActive=input.IsActive}; user.PasswordHash=hasher.HashPassword(user,string.IsNullOrWhiteSpace(input.Password)?"123456":input.Password); db.Users.Add(user); await db.SaveChangesAsync(); db.ActivityLogs.Add(new ActivityLog{Action=$"Created user: {user.FullName}",Entity="User",EntityId=user.Id,UserId=GetUserId()}); await db.SaveChangesAsync(); return Ok(new{user.Id,user.FullName,user.Email,Role=user.Role.ToString()}); }
 [Authorize(Roles="Admin")][HttpPut("{id}")] public async Task<IActionResult> Edit(int id,User input){var x=await db.Users.FindAsync(id);if(x==null)return NotFound();x.FullName=input.FullName;x.Email=input.Email;x.Role=input.Role;x.DepartmentId=input.DepartmentId;x.IsActive=input.IsActive;await db.SaveChangesAsync();db.ActivityLogs.Add(new ActivityLog{Action=$"Updated user: {x.FullName}",Entity="User",EntityId=x.Id,UserId=GetUserId()});await db.SaveChangesAsync();return Ok(x);}
 [Authorize(Roles="Admin")][HttpDelete("{id}")] public async Task<IActionResult> Delete(int id){var x=await db.Users.FindAsync(id);if(x==null)return NotFound();db.Users.Remove(x);await db.SaveChangesAsync();db.ActivityLogs.Add(new ActivityLog{Action=$"Deleted user: {x.FullName}",Entity="User",EntityId=id,UserId=GetUserId()});await db.SaveChangesAsync();return NoContent();}
}
